name: PEP 8 Check

on:
  push:
    branches:
      - main  # Zmień na nazwę swojej głównej gałęzi

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.4


      - name: Set up Python
        uses: actions/setup-python@v2.4.7
        with:
          python-version: 3.8  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Run Pycodestyle
        run: pycodestyle .
